Intro

Créé 2012
Ansible = Infrastrure as code + deploiement de configs + installation + orchestrateur. Pas besoin d'agent installé sur les machines distantes
sur lesquelles on veut travailler. Via du SSH
à base de python

-Control node:
	noeud disposant de ansible et permettant de déployer
	accès ssh aux autres machines
      sécurité importante

-Managed node:
	serveurs cibles
	permet la con ssh
	élévation de privilèges via le user

-Inventory:
	inventaires des machines(ip,dns)
	format ini (plat) ou format yaml
	les variables(host_vars, group_vars)
	statiques(fichiers) ou dynamique (api via script)

-Groupes:
	dans un inventaire les machines peuvent etre regroupées(serveur, database..)	
	possibilité de créer différents niveaux > arbre (parents/enfants)

-Groups vars:
	variables d'un mm groupe
	défini dans le fichier central d'inventory
	ou dans un rep. spécifique(reconnu par ansible)

-Host vars:
	variables pour un serveur en particulier
	surcharge d'autres variables définie plus haut dans l'arbre-ex-group


-Exemple d'inventory:
	inventory.yml
		host_vars/
		group_vars/

-Tasks:
	actions variées(user, group, command, module)
	format yml

-Modules:
	ensemble d'action ciblées sur une utilisation commune
	pour un outil donnée: Ex. postgres, mysql, vmware...
	chacune des ses actions est utilisable via une tasks
	chaque action prend des options
	les actions peuvent fournir un retour (id, result)

-Roles:
	ensemble d'action coordonnées pour réaliser un ensemble cohérent(installation nginx, et le config etc)
	peut etre partager sur le hub ansible galaxy

-Playbooks:
	un fichier (et rien d'autres...)
	applique des roles à un inventory
	inventory > playbook < roles

-Plugins:
	modifie ou augmente les capacité de ansible
	de différent manière: output, inventory dynamique, stratégy, tests...
	



	

	






